server:
  port: 8080

spring:
  application:
    name: mystore
  datasource:
    url: jdbc:h2:mem:storedb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      username: sa
      password: password


scheduler:
  enabled: true
time:
  to:
    delete: 30